version: "3.8"

services:
  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - ml-service
