version: "3.8"

services:
  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./hf-cache:/root/.cache/huggingface

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - ml-service

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      # - VITE_API_URL=http://backend:5001
      - VITE_API_URL=http://localhost:5001
