replicaCount: 1

image:
  repository: 626635431082.dkr.ecr.us-east-1.amazonaws.com/product-review-ml-service
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: "ClusterIP"
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
