replicaCount: 1

image:
  repository: 626635431082.dkr.ecr.us-east-1.amazonaws.com/product-review-ml-service
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: "ClusterIP"
  port: 8000

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"


nodeSelector: {}
tolerations: []
affinity: {}
