replicaCount: 1

image:
  repository: 626635431082.dkr.ecr.us-east-1.amazonaws.com/product-review-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5001

resources: {}
